/**
 * pdfNormalize.service.js
 * ---------------------------------------------------------------------------
 * Server-side PDF normalization for teacher uploads.
 *
 * WHY THIS EXISTS
 * PDFs exported from Word/PowerPoint or generated by AI tools frequently
 * break in client-side viewers: non-embedded fonts, damaged cross-reference
 * tables, exotic object streams. Image-only PDFs always render fine.
 *
 * HOW IT FIXES FILES (no Ghostscript — it is a native binary that cannot
 * run on Vercel serverless). Instead this pipeline re-renders every page
 * with the SAME engine the browser viewer uses (pdfjs-dist), draws each
 * page into a raster buffer (@napi-rs/canvas, prebuilt native binding),
 * and rebuilds a brand-new, standards-compliant PDF with pdf-lib where
 * every page is a full-bleed image. Pixels cannot have font problems, so
 * whatever renders correctly here renders correctly everywhere.
 *
 * FAILURE POLICY (required behaviour)
 * Normalization is best-effort. If ANY step fails (corrupt structure,
 * timeout, memory), the error is logged clearly for debugging and the
 * ORIGINAL buffer is returned so the upload still completes. Teachers are
 * never blocked and never asked to fix files themselves.
 */

const MAX_NORMALIZED_PAGES = 30;
const NORMALIZE_TIMEOUT_MS = 25000;

/** Lazily resolved heavy dependencies (keeps cold starts fast). */
let lazyModules = null;

async function getModules() {
  if (!lazyModules) {
    const [{ createCanvas, DOMMatrix, Path2D, ImageData }, pdfLibModule] =
      await Promise.all([import("@napi-rs/canvas"), import("pdf-lib")]);

    // pdfjs-dist expects these browser globals to exist while rendering.
    // @napi-rs/canvas ships compatible implementations — register them
    // BEFORE pdfjs loads or complex pages (curves/transforms) render wrong.
    globalThis.DOMMatrix = globalThis.DOMMatrix || DOMMatrix;
    globalThis.Path2D = globalThis.Path2D || Path2D;
    globalThis.ImageData = globalThis.ImageData || ImageData;

    // pdfjs-dist v3 ships a CommonJS legacy build for Node usage.
    lazyModules = {
      createCanvas,
      PDFDocument: pdfLibModule.PDFDocument,
      pdfjs: await import("pdfjs-dist/legacy/build/pdf.js"),
    };
  }
  return lazyModules;
}

/** Absolute path to pdfjs standard fonts, used when a PDF omits base-14 fonts. */
function getStandardFontDataUrl() {
  const path = require("path");
  return path.join(
    path.dirname(require.resolve("pdfjs-dist/package.json")),
    "standard_fonts",
    path.sep
  );
}

/**
 * Renders one pdf.js page into a PNG buffer at ~150 DPI.
 *
 * @param {object} page - A pdf.js PDFPageProxy.
 * @returns {Promise<Uint8Array>} PNG-encoded page image.
 */
async function renderPageToPng(page) {
  const { createCanvas } = await getModules();

  const baseViewport = page.getViewport({ scale: 1 });
  const targetDpi = 150;
  const scale = (targetDpi / 72) * 1;
  const viewport = page.getViewport({ scale });

  const canvas = createCanvas(
    Math.ceil(viewport.width),
    Math.ceil(viewport.height)
  );
  const context = canvas.getContext("2d");
  context.fillStyle = "#ffffff";
  context.fillRect(0, 0, canvas.width, canvas.height);

  await page.render({
    canvasContext: context,
    viewport,
    background: "#ffffff",
  }).promise;

  return canvas.encode("png");
}

/**
 * Core pipeline: parse with pdf.js, rasterize every page, rebuild with pdf-lib.
 * Throws on failure so callers can decide fallback behaviour.
 *
 * @param {Buffer} originalBuffer - The uploaded PDF bytes.
 * @returns {Promise<{buffer: Buffer, pages: number}>}
 */
async function rebuildPdf(originalBuffer) {
  const { PDFDocument, pdfjs } = await getModules();

  const loadingTask = pdfjs.getDocument({
    data: new Uint8Array(originalBuffer),
    useSystemFonts: false,
    standardFontDataUrl: getStandardFontDataUrl(),
    verbosity: 0,
  });

  const sourceDoc = await loadingTask.promise;
  try {
    const pageCount = Math.min(sourceDoc.numPages, MAX_NORMALIZED_PAGES);

    const outputDoc = await PDFDocument.create();
    outputDoc.setTitle("Normalized lesson material");
    outputDoc.setProducer("MSAsmaa PDF normalizer");

    for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
      const page = await sourceDoc.getPage(pageNumber);
      const pngBytes = await renderPageToPng(page);

      const embeddedImage = await outputDoc.embedPng(pngBytes);
      const originalSize = page.getViewport({ scale: 1 });

      const newPage = outputDoc.addPage([
        originalSize.width,
        originalSize.height,
      ]);
      newPage.drawImage(embeddedImage, {
        x: 0,
        y: 0,
        width: originalSize.width,
        height: originalSize.height,
      });
    }

    const outputBytes = await outputDoc.save({ useObjectStreams: true });
    return { buffer: Buffer.from(outputBytes), pages: pageCount };
  } finally {
    await loadingTask.destroy();
  }
}

/**
 * Normalizes an uploaded PDF with a hard timeout and graceful degradation.
 * Never throws for content problems: callers always receive usable bytes.
 *
 * @param {Buffer} originalBuffer - The uploaded PDF bytes.
 * @param {string} [logLabel] - Context for backend logs (e.g. the lesson ID).
 * @returns {Promise<object>} { buffer, normalized, pages?, reason? }
 */
async function normalizePdf(originalBuffer, logLabel = "upload") {
  if (!originalBuffer || originalBuffer.length < 100) {
    console.error(`[pdfNormalize:${logLabel}] Rejected: buffer missing or too small.`);
    return { buffer: originalBuffer, normalized: false, reason: "empty-or-tiny" };
  }

  try {
    const rebuildPromise = rebuildPdf(originalBuffer);
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(
        () => reject(new Error(`Normalization timed out after ${NORMALIZE_TIMEOUT_MS}ms`)),
        NORMALIZE_TIMEOUT_MS
      );
    });

    const { buffer, pages } = await Promise.race([rebuildPromise, timeoutPromise]);

    // Sanity check: a rebuild that somehow produced nothing usable falls back.
    if (!buffer || buffer.length < 200) {
      throw new Error("Rebuilt PDF was unexpectedly tiny");
    }

    console.log(
      `[pdfNormalize:${logLabel}] OK — ${pages} page(s), ` +
        `${(originalBuffer.length / 1024).toFixed(0)}KB -> ${(buffer.length / 1024).toFixed(0)}KB`
    );
    return { buffer, normalized: true, pages };
  } catch (error) {
    console.error(
      `[pdfNormalize:${logLabel}] FAILED (${error.message}). Storing ORIGINAL bytes instead — ` +
        "the file may be severely corrupted; investigate if students report rendering issues."
    );
    return { buffer: originalBuffer, normalized: false, reason: error.message };
  }
}

module.exports = { normalizePdf };
